### PR TITLE
updated background_layers.sh, with clipping

### PR DESCRIPTION
**Pull request by smnorris**
- pulls bcfishpass related datasets from pre-processed flatgeobuf files on S3, using attribute query to clip to AOI
- uses attribute query to clip FWA data coming from bcgw/pgfs
- for all other BCGW WFS data, clipping to AOI is done by ogr2ogr (slow but reliable)

### CODE REVIEW

**Comment by smnorris** [comment]
Datasets that seem reasonable to add to the cached set of fgb files:
- fiss_fish_obsrvtn_events_vw  (from bcfishobs)
- mot_culverts_sp
- gba_railway_tracks_sp
- ften_road_section_lines_svw

My proposal is for these files to be refreshed weekly. The weekly replication to postgres is already mostly set up, this is not a lot of additional work. 

In theory, if all data sources noted in bcfishpass/qgis were synced to this spot, these files could also be used by QGIS for general bcfishpass mapping (in place of a connection to a bcfishpass postgres database).

**Comment by smnorris** [comment]
See https://github.com/NewGraphEnvironment/dff-2022/pull/89/commits/401a37a0bdf7c3e86267f27c8c155f5182a80064 for instructions.

**Comment by smnorris** [comment]
Only 3min for entire Skeena, thats pretty good.
```
$ time ./bcdata.sh "'BABL','BABR','BULK','KISP','KLUM','LKEL','LSKE','MORR','MSKE','SPAT','SUST','TAKL','USKE','ZYMO'"
real	2m45.054s
user	0m30.070s
sys	0m6.408s
```

**Review by NewGraphEnvironment — APPROVED** [review]
whoa. Sick moves Norris. Thank you! see if I can find time to try to spin up before leaving tomo. hair straight back ...

**Pull request merged**
